apiVersion: batch/v1
kind: Job
metadata:
  name: sk108-kaniko-build-667a55ad
  namespace: skala-practice
  labels:
    app: sk108
spec:
  template:
    metadata:
      labels:
        app: sk108
    spec:
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:latest
        args:
          - --dockerfile=/workspace/Dockerfile
          - --context=dir:///workspace
          - --destination=amdp-registry.skala-ai.com/skala25a/sk108-kaniko-build-app:1.0.0-kaniko
        volumeMounts:
          - name: kaniko-secret
            mountPath: /kaniko/.docker
          - name: workspace
            mountPath: /workspace
      restartPolicy: Never
      volumes:
        - name: kaniko-secret
          secret:
            secretName: harbor-registry-secret
            items:
              - key: .dockerconfigjson
                path: config.json  # /kaniko/.docker/config.json 파일로 마운트됨
        - name: workspace
          configMap:  # 또는 PVC, emptyDir, gitRepo 등
            name: kaniko-app-workspace

