apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: push-pipeline-sa
  namespace: skala-tekton
spec:
  params:
    - name: git-url
      type: string
      description: "Git repository URL"
    - name: git-revision
      type: string
      default: "main"
      description: "Git branch to checkout"
    - name: image-registry
      type: string
      description: "Docker image registry"
    - name: image-name
      type: string
      description: "Docker image name"
    - name: image-tag
      type: string
      default: "latest"
      description: "Docker image tag"
  workspaces:
    - name: shared-workspace
    - name: maven-settings
    - name: maven-local-repo
  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
        kind: Task
      params:
        - name: url
          value: "$(params.git-url)"
        - name: revision
          value: "$(params.git-revision)"
      workspaces:
        - name: output
          workspace: shared-workspace

    - name: maven-build
      taskRef:
        name: maven
        kind: Task
      runAfter:
        - git-clone
      params:
        - name: GOALS
          value:
            - "clean"
            - "package"
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: maven-settings
          workspace: maven-settings
        - name: maven-local-repo
          workspace: maven-local-repo

    - name: kaniko-build-push
      taskRef:
        name: kaniko
        kind: Task
      runAfter:
        - maven-build
      params:
        - name: DOCKERFILE
          value: "Dockerfile"
        - name: IMAGE
          value: "$(params.image-registry)/$(params.image-name):$(params.image-tag)"
      workspaces:
        - name: source
          workspace: shared-workspace


