apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: sk000-springboot-binding
  namespace: skala-tekton
spec:
  params:
    - name: git-url
      value: $(body.repository.clone_url)
    - name: git-revision
      value: $(body.ref)

