apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: springboot-deploy-run-v00001
  namespace: skala-tekton
spec:
  pipelineRef:
    name: springboot-push-pipeline
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        metadata:
          name: springboot-pvc-v00001
        spec:
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 5Gi
          storageClassName: amdp-dev-efs
    - name: maven-settings
      persistentVolumeClaim:
        claimName: $(workspaces.shared-workspace.claimName)  # shared-workspace PVC를 참조
  podTemplate:
    securityContext:
      fsGroup: 911  # 볼륨을 사용하는 그룹 ID
      runAsUser: 911  # Pod를 실행하는 사용자 ID
      runAsGroup: 911  # Pod를 실행하는 그룹 ID
  params:
    - name: git-url
      value: "https://github.com/himang10/tekton-source.git"
    - name: git-revision
      value: "master"
    - name: image-registry
      value: "amdp-registry.skala-ai.com/skala25a"
    - name: image-name
      value: "springboot-app"
    - name: image-tag
      value: "1.0"
  serviceAccountName: pipeline-sa
