apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJhbWRwLXJlZ2lzdHJ5LnNrYWxhLWFpLmNvbSI6eyJ1c2VybmFtZSI6InJvYm90JHNrYWxhMjVhIiwicGFzc3dvcmQiOiIxcUI5Y3l1c2JOQ29tWlBIQWRqTklGV2luZjUyeGFCSiIsImF1dGgiOiJjbTlpYjNRa2MydGhiR0V5TldFNk1YRkNPV041ZFhOaVRrTnZiVnBRU0VGa2FrNUpSbGRwYm1ZMU1uaGhRa289In19fQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: harbor-registry-secret
  namespace: skala-tekton
  annotations:
    tekton.dev/docker-0: https://amdp-registry.skala-ai.com 
type: kubernetes.io/dockerconfigjson
