apiVersion: v1
kind: Secret
metadata:
  name: jenkins-admin-secret
  namespace: jenkins
type: Opaque
stringData:
  username: admin  # base64 encoded "admin"
  password: admin  # base64 encoded "admin" - 실제 운영에서는 강력한 비밀번호 사용
