apiVersion: v1
kind: Service
metadata:
  name: sk108-myfirst-api-server
  namespace: skala-practice
  labels:                     # ✅ 여기 추가
    app: sk108-myfirst-api-server
spec:
  selector:
    app: sk108-myfirst-api-server
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: mgmt
      protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
